{% set name = "occultercut" %}
{% set version = "1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: "https://downloads.sourceforge.net/project/{{ name }}/OcculterCut_v{{ version }}.tar.gz"
  md5: 0041f278bd2c74b10e00f252b61e25ba

build:
  number: 0
  target_platform:
    - linux-64

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - gnuplot
    - libgomp
  run_exports:
    - bin/OcculterCut

test:
  commands:
    - OcculterCut | grep "OcculterCut"

about:
  license: GPL3
  summary: 'A package for measuring the local GC-content bias in genomes and fungal species'
