{% set name = "ripcal" %}
{% set version = "2.0" %}
{% set sha256 = "6f18af1c6fedde17430e023e3a5c1ab56f14910694d83ba90ee738d8d48188bd" %}

package:
  name: '{{ name }}'
  version: '{{ version }}'

source:
  url: "https://downloads.sourceforge.net/project/RIPCAL/RIPCAL_{{ version }}/{{ name }}_install.zip"
  sha256: '{{ sha256 }}'

build:
  number: 0
  noarch: generic

requirements:
  host:
    - unzip
  run:
    - perl
    - perl-cwd
    - perl-getopt-long
    - perl-math-round
    - perl-mime-base64
    - perl-file-spec-win32
    - perl-bioperl
    - perl-tk
    - perl-gd

test:
  commands:
    - ripcal --help
    - derip --help

about:
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: COPYING
  summary: 'RIPCAL is used for the bioinformatic analysis of repeat-induced point mutation (RIP) in fungal genome sequences'
  home: https://sourceforge.net/projects/ripcal

extra:
  identifiers:
    - https://doi.org/10.1186/1471-2105-9-478
  recipe-maintainers:
    - KristinaGagalova
